spring:
  config:
    import: optional:file:env.properties
  application:
    name: ${NAME_GATE}

server:
  port: ${PORT_GAT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREK_URL}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true